name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    
permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "." 

jobs:
  notify_pull_request_google_chat:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Google Chat
        if: ${{ always() }} 
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          title: ${{ 'Déploiement réussi sur Thotify ! 🚀' }}
          subtitle: ${{  'Les modifications ont été fusionnées avec succès ! 😻' }}
          additionalSections: |
            [              
              {
                "header": "Détails de la fusion",
                "collapsible": true,
                "widgets": [
                  { "decoratedText": { "text": "- Titre du commit  : ${{github.event.commits[0].message}}" } },
                  { "decoratedText": { "text": "- Auteur : ${{ github.event.commits[1].author.username }}" } }
                ]
              },
              {
                "header": "Résultats des jobs",
                "collapsible": true,
              }
            ]