name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    
permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "." 

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
  notify_pull_request_google_chat:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Google Chat
        if: ${{ always() }} # Utilisez 'always' pour vous assurer que la notification est envoyée même en cas d'échec des étapes précédentes
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          title: ${{ needs.deploy.result == 'success' && 'Déploiement réussi sur Thotify ! 🚀' || 'Échec du déploiement sur Thotify ❌' }}
          subtitle: ${{ needs.deploy.result =='success' && 'Les modifications ont été fusionnées avec succès ! 😻' || 'Il y à eu une erreur lors de la mise en ligne..' }}
          additionalSections: |
            [              
              {
                "header": "Détails de la fusion",
                "collapsible": true,
                "widgets": [
                  { "decoratedText": { "text": "- Titre du commit  : ${{github.event.commits[0].message}}" } },
                  { "decoratedText": { "text": "- Auteur : ${{ github.event.commits[1].author.username }}" } }
                ]
              },
              {
                "header": "Résultats des jobs",
                "collapsible": true,
                "widgets": [
                  { "decoratedText": { "text": "- Deployment : ${{ needs.deploy.result }}" } }
                ]
              }
            ]